### PR TITLE
Add project milestones,issue notes and labels API.

### PR DESCRIPTION
**Pull request by Stel000**
Add project milestones,issue notes and labels API.

### CODE REVIEW

**Comment by gmessner** [comment]
@Stel000 
Thank you for the contribution.  Two things I would like to see changed before approving this:

1) MIlestone is one word, so all references should be "Milestone" not "MileStone".

2) In the Notes API, the methods that were renamed by adding "Issue" in the name, need to be new methods, and the old methods need to be marked "deprecated".  Public APIs like this must deprecate with a warning when the deprecated methods will be removed.

**Comment by gmessner** [comment]
@Stel000 
I'm going to go ahead and merge your code and then make the changes I suggested above.  WIll let you know when that is completed.

**Comment by gmessner** [comment]
@Stel000 
I've made the mods and added Javadocs to the MilestonesApi, LabelsApi still needs Javadocs added, it would be appreciated if you could add them to the LabelsApi.

**Comment by Stel000** [comment]
@gmessner Eh,it is something wrong with Labels Api.It already fixed in my repo.But the Session Api looks like wrong with gitlab-10.2.2.I will push when i fix this.

**Comment by gmessner** [comment]
@Stel000 
GitLab CE 10.2.0 removed the Session API and endpoint along with private tokens.  I am currently looking into why GitLab did this and how to address the issue.

Also, make sure to pull the latest from this repo before you submit your changes, there are differences between your original submission and gitlab4j-api.

**Comment by gmessner** [comment]
@Stel000 
Here are the notes from the 10.2.0 release, you'll see that some security changes were made that removed the Session API:

10.2.0 (2017-11-22)
Security (4 changes)
* Upgrade Ruby to 2.3.5 to include security patches. !15099
* Prevent OAuth phishing attack by presenting detailed wording about app to user during authorization.
* Convert private tokens to Personal Access Tokens with sudo scope.
* Remove private tokens from web interface and API.

Removed (5 changes)
* Remove help text from group issues page and group merge requests page. !14963
* Remove overzealous tooltips in projects page tabs. !15017
* Stop merge requests from fetching their refs when the data is already available. !15129
* Remove update merge request worker tagging.
* Remove Session API now that private tokens are removed from user API endpoints.

**Comment by Stel000** [comment]
@gmessner Maybe can authroization with OAuth by Password Credentials?By this can get AccessToken.

**Pull request merged**
