### PR TITLE
Add support for parsing weeks in issue estimates.

### PR DESCRIPTION
**Pull request by enveraltin**

### CODE REVIEW

**Comment by enveraltin** [comment]
Hey,

We had some estimates specified in weeks, and it failed of course 😄

**Comment by korayucar** [comment]
toString method must change also.

**Comment by gmessner** [comment]
@enveraltin
I ended up not merging this request, but have fully incorporated your change in addition to fixing the toString() method and adding unit tests for same.  The latest release includes these changes.

**Comment by enveraltin** [comment]
Thanks!

**Pull request merged**
