### PR TITLE
Adding changelog

### PR DESCRIPTION
**Pull request by tomasbjerre**
I noticed there was no changelog in the repo. You might be interested in using this plugin to generate it.

Else, just feel free to close this PR =)

### CODE REVIEW

**Comment by gmessner** [comment]
@tomasbjerre 
Do you know if there is a way to have the changelog template somewhere other than pom.xml ?

**Comment by tomasbjerre** [comment]
Yes there is a configuration attribute for that, templateFile.

**Comment by gmessner** [comment]
Can you make that change and update the PR?  I'll merge when that is completed.

**Comment by tomasbjerre** [comment]
Yes, I can change it later today.

**Comment by tomasbjerre** [comment]
@gmessner Updated.

**Comment by gmessner** [comment]
@tomasbjerre 
As always, thank you for your contribution.

**Comment by gmessner** [comment]
@tomasbjerre 
I am getting the following error in the pom.xml:
```
Plugin execution not covered by lifecycle configuration: se.bjurr.gitchangelog:git-changelog-maven-plugin:1.59:git-changelog (execution: GenerateGitChangelog, phase: generate-sources)
```

Also, when importing into Eclipse I get the following error:
```
No marketplace entries found to handle git-changelog-maven-plugin:1.59:git-changelog in Eclipse.  Please see Help for more information.
```
Can these be corrected?

**Comment by tomasbjerre** [comment]
Looks like you can tell m2e to ignore the plugin: https://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin

**Comment by tomasbjerre** [comment]
Or, you want it out of the pom. You can do:
```
mvn se.bjurr.gitchangelog:git-changelog-maven-plugin:git-changelog
```

And rename the template to `changelog.mustache`.

And issue this command manually whenever you want to update the changelog.

**Comment by gmessner** [comment]
@tomasbjerre 
Enclosing the plugins in a ```<pluginManagement>``` tag in the pom fixed the error.  Thanks for this info.

**Pull request merged**
