### PR TITLE
 WIP feat(logging): option to allow http request/response logging

### PR DESCRIPTION
**Pull request by jgoldhammer**
Currently it is not possible to see monitor the http requests/responses via logging.
This PR adds the capability. I am totally open for changes.

### CODE REVIEW

**Comment by gmessner** [comment]
@jgoldhammer 
Absolutely agree that it would be extremely useful to provide the ability to log the requests to and responses from the GitLab API.  The goals for adding this type of logging would be as follows:

1 - Minimal impact on the current code. 
2 - The logging should be activated in one or both of the following ways:
   *  Via standard java.util.logging configuration file
   * Via a method call on the GitLabApi instance after creation, with a fluent interface. I.e.:
```
// With default Logger
GitLabApi gitLabApi = new GitLabApi("http://your.gitlab.server.com", "YOUR_PRIVATE_TOKEN").withLogging(Level.FINE);

// With consumer provided Logger
GitLabApi gitLabApi = new GitLabApi("http://your.gitlab.server.com", "YOUR_PRIVATE_TOKEN").withLogging(loggerInstance, Level.FINE);
```
And a standard non-fluent way:
```
// With default Logger
GitLabApi gitLabApi = new GitLabApi("http://your.gitlab.server.com", "YOUR_PRIVATE_TOKEN");
gitLabApi.setLogging(Level.FINE);

// With consumer provided Logger
GitLabApi gitLabApi = new GitLabApi("http://your.gitlab.server.com", "YOUR_PRIVATE_TOKEN");
gitLabApi.setLogging(loggerInstance, Level.FINE);
```

3 - The default Logger should be shared by all classes in the GitLab4J-API library.  There are currently two Logger instances in the library, one in ```org.gitlab4j.api.systemhooks.SystemHookManager``` and another in ```org.gitlab4j.api.webhook.WebHookManager```. I would suggest that these two Logger instances use the yet to be introduced GitLabApi default logger.

Because this is such a significant addition, I would request that I make the changes and ask that you review what I do.  I believe it will provide the quickest way to get this done, and right now I do not have time to go through a thorough review process of someone elses code.

Let me know what you think about my proposal.

**Comment by jgoldhammer** [comment]
I am totally fine with it. Please go ahead. 
Thanks!

**Comment by gmessner** [comment]
@jgoldhammer 
I'm ready to submit the PR, could you add an issue to request this feature?  Once that is in I'll submit the PR for your review.

**Comment by jgoldhammer** [comment]
https://github.com/gmessner/gitlab4j-api/issues/228

**Pull request closed without merging**
